FROM mcr.microsoft.com/vscode/devcontainers/base:0-focal

RUN echo 'set show-all-if-ambiguous on' >> /etc/inputrc
RUN echo '"\\e[Z": menu-complete' >> /etc/inputrc

# Normally next there will be some tools installed like .Net, Node.js and Angular
